#!/usr/bin/env python3
"""Cursor prompt deeplinks for OrgWave — https://cursor.com/docs/reference/deeplinks (confirm to run)."""
from __future__ import annotations

import argparse
import re
import urllib.parse
from pathlib import Path

MAX_LEN = 8000
REPO_ROOT = Path(__file__).resolve().parent.parent
CATALOG = REPO_ROOT / "catalog.yaml"
RUN_MD = REPO_ROOT / "docs" / "run-in-cursor.md"

# Single place for “Run in Cursor” badge markup (used for every playbook row).
RUN_BUTTON_ALT = "Run"
RUN_BUTTON_BADGE_IMAGE = (
    "https://img.shields.io/badge/Run_in-Cursor-111111?style=flat-square"
)


def run_in_cursor_badge(deeplink_url: str) -> str:
    """Common markdown for one Run-in-Cursor control (shields badge → deeplink)."""
    return f"[![{RUN_BUTTON_ALT}]({RUN_BUTTON_BADGE_IMAGE})]({deeplink_url})"


def build_prompt(playbook_id: str) -> str:
    return f"""You are running OrgWave. Open this orgwave-playbooks repository as the Cursor workspace (clone it first if needed).

1. Follow .cursor/rules/orgwave-orchestrator.mdc and load playbook id `{playbook_id}` from catalog.yaml and playbooks/{playbook_id}/SKILL.md.
2. Ask me for the GitHub org if unknown. Use global GitHub MCP to list/filter repos per the playbook (or use a discovery JSON file from the latest Actions run if I attach it).
3. Show a numbered table of candidate services and STOP until I select which repos to run.
4. For each selected service: apply the playbook, run tests if applicable, push branches, open one PR per service. Do not merge."""


def web_url(playbook_id: str) -> str:
    q = urllib.parse.urlencode({"text": build_prompt(playbook_id)})
    url = f"https://cursor.com/link/prompt?{q}"
    if len(url) > MAX_LEN:
        raise ValueError(f"URL length {len(url)} exceeds {MAX_LEN} for playbook {playbook_id!r}")
    return url


def desktop_url(playbook_id: str) -> str:
    q = urllib.parse.urlencode({"text": build_prompt(playbook_id)})
    url = f"cursor://anysphere.cursor-deeplink/prompt?{q}"
    if len(url) > MAX_LEN:
        raise ValueError(f"Desktop URL length {len(url)} exceeds {MAX_LEN} for playbook {playbook_id!r}")
    return url


def parse_catalog(path: Path) -> list[tuple[str, str | None]]:
    """Return [(id, name), ...] from catalog.yaml (no PyYAML dependency)."""
    text = path.read_text(encoding="utf-8")
    chunks = re.split(r"(?m)^\s*-\s+id:\s*", text)
    out: list[tuple[str, str | None]] = []
    for chunk in chunks[1:]:
        first, _, rest = chunk.partition("\n")
        pid = first.strip().strip("\"'")
        if not pid or pid.startswith("#"):
            continue
        nm = re.search(r"(?m)^\s+name:\s*(.+)$", chunk)
        name = nm.group(1).strip().strip("\"'") if nm else None
        out.append((pid, name))
    return out


def markdown_buttons(entries: list[tuple[str, str | None]]) -> str:
    lines = [
        "# Run in Cursor",
        "",
        "One click opens Cursor with a **prefilled prompt** for that playbook (you still confirm before it runs).",
        "",
        "| Playbook | Run |",
        "|----------|-----|",
    ]
    for pid, name in entries:
        label = name or pid
        lines.append(f"| **{label}** (`{pid}`) | {run_in_cursor_badge(web_url(pid))} |")
    lines.extend(
        [
            "",
            "---",
            "",
            "**Do not edit this file by hand.** It is produced from `catalog.yaml` by",
            "`scripts/generate-orgwave-deeplink.py`.",
            "",
            "On push to `main`, the workflow **Regenerate Run in Cursor** updates this file",
            "when `catalog.yaml` or the generator script changes.",
            "",
            "Local preview:",
            "",
            "```bash",
            "python3 scripts/generate-orgwave-deeplink.py --write-docs",
            "```",
            "",
        ]
    )
    return "\n".join(lines) + "\n"


def main() -> None:
    p = argparse.ArgumentParser(description="Generate Cursor deeplinks for OrgWave playbooks")
    p.add_argument("playbook_id", nargs="?", help="Single playbook id (folder under playbooks/)")
    p.add_argument("--desktop", action="store_true", help="Emit cursor:// URL for one id")
    p.add_argument(
        "--write-docs",
        action="store_true",
        help=f"Write docs/run-in-cursor.md for every playbook in catalog.yaml",
    )
    p.add_argument(
        "--print-all",
        action="store_true",
        help="Print markdown table to stdout (same as --write-docs but no file)",
    )
    args = p.parse_args()

    if args.write_docs or args.print_all:
        entries = parse_catalog(CATALOG)
        body = markdown_buttons(entries)
        if args.print_all:
            print(body, end="")
        else:
            RUN_MD.parent.mkdir(parents=True, exist_ok=True)
            RUN_MD.write_text(body, encoding="utf-8")
            print(f"Wrote {RUN_MD}")
        return

    if not args.playbook_id:
        p.error("pass playbook_id, or use --write-docs / --print-all")
    if args.desktop:
        print(desktop_url(args.playbook_id))
    else:
        print(web_url(args.playbook_id))


if __name__ == "__main__":
    main()
